const people=[
{name:'Sam Altman',tag:'OpenAI',color:'#ddebba',prompt:'Find a clip of Sam talking about the future of AGI'},
{name:'Dario Amodei',tag:'Anthropic',color:'#f2cfbb',prompt:'Find a clip of Dario talking about AI safety'},
{name:'Demis Hassabis',tag:'Google DeepMind',color:'#d8d6f1',prompt:'Find a clip of Demis talking about scientific discovery'},
{name:'Geoffrey Hinton',tag:'Deep learning',color:'#c9dde8',prompt:'Find a clip of Geoffrey talking about AI risks'},
{name:'Yoshua Bengio',tag:'AI research',color:'#eee0aa',prompt:'Find a clip of Yoshua talking about safe AI'},
{name:'Max Tegmark',tag:'Future of Life',color:'#cce3d6',prompt:'Find a clip of Max talking about the future of humanity'},
{name:'Eliezer Yudkowsky',tag:'AI alignment',color:'#e9ccd8',prompt:'Find a clip of Eliezer explaining AI alignment'}
].map(p=>({...p,slug:p.name.toLowerCase().replaceAll(' ','-')}));
const mode=new URLSearchParams(location.search).get('mode')||'a';document.body.className='mode-'+mode;
let selected=0;let messages=[];
const arrow='<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 19V5m-6 6 6-6 6 6"/></svg>';
const scissors='<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="m8 8 12 12M8 16 20 4"/></svg>';
function photo(p,cls=''){return `<img class="${cls}" src="assets/${p.slug}.jpg" alt="${p.name}">`;}
function roster(){return `<div class="roster" aria-label="Choose a speaker">${people.map((p,i)=>`<button class="person ${i===selected?'selected':''}" data-person="${i}" aria-pressed="${i===selected}" style="--card:${p.color}"><span class="portrait">${photo(p)}<span class="check" aria-hidden="true">✓</span></span><span class="person-name">${p.name}</span><span class="person-tag">${p.tag}</span></button>`).join('')}</div>`;}
function composer(){let p=people[selected];return `<form class="composer"><label class="sr-only" for="prompt">Describe the ${p.name} clip you want to find</label><textarea id="prompt" rows="2" placeholder="${(mode==='c'||mode==='d')?'What are you looking for?':p.prompt+'…'}"></textarea><div class="composer-bottom"><span class="scope">${photo(p)}<span>Searching <strong>${p.name}</strong></span></span><button class="send" type="submit" aria-label="Find a clip">${arrow}</button></div></form><p class="composer-hint">Real quotes. Original videos. Right to the moment.</p>`;}
function suggestions(){return `<div class="suggestions"><span>Try a little inspiration</span><div>${['AI could change everything','The risks of superintelligence','A surprising prediction'].map((x,i)=>`<button data-suggestion="${i}">${['✧','↗','⚡'][i]} ${x}</button>`).join('')}</div></div>`;}
function heading(){let p=people[selected];return `<p class="eyebrow">${scissors} BIG IDEAS. PERFECT LITTLE CLIPS.</p><h1>Find a <span class="speaker-title">${p.name}</span> clip<span class="bang">!</span></h1><p class="intro">You have a moment in mind. Let’s dig it up.<br class="desktop-break"> Search the conversations behind the big ideas.</p>`;}
function render(){let p=people[selected];const app=document.getElementById('app');
if(mode==='d'){renderSwipe(app);}
else if(mode==='a'){app.innerHTML=`<section class="deck-hero">${heading()}<div class="picker-label"><span>THE VOICES SHAPING AI</span><span>Pick your person ↓</span></div>${roster()}<div class="chat-start">${composer()}${suggestions()}</div></section>`;}
else if(mode==='b'){app.innerHTML=`<section class="spotlight"><div class="spotlight-copy">${heading()}${composer()}${suggestions()}</div><div class="spotlight-art" style="--card:${p.color}"><div class="orb"></div><span class="sticker">Good questions.<br>Great clips.</span><div class="feature-card">${photo(p)}<div class="feature-caption"><div><h2>${p.name}</h2><p>${p.tag}</p></div><span>${scissors}</span></div></div><span class="photo-note">Your next “wait, they said that?”</span><span class="scribble" aria-hidden="true">✳</span></div></section><section class="spotlight-picker"><div class="picker-label"><span>WHO’S ON YOUR MIND?</span><span>A different voice, a new rabbit hole.</span></div>${roster()}</section>`;}
else{app.innerHTML=`<section class="workspace"><aside><div class="sidebar-heading"><span>YOUR VOICES</span><span>07</span></div>${roster()}<div class="sidebar-note">Follow the thought.<br>Find the moment. ${scissors}</div></aside><div class="chat-room"><div class="room-heading"><span><i></i> ${p.name}’s conversations</span><button id="new-chat">＋ New chat</button></div><div class="room-welcome"><div class="welcome-photo" style="--card:${p.color}">${photo(p)}<span>${scissors}</span></div>${heading()}${suggestions()}</div><div class="room-composer">${composer()}</div></div></section>`;}
bind();if(mode==='d')bindSwipe();}
function bind(){document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{const scroll=document.querySelector('.roster').scrollLeft;selected=Number(b.dataset.person);messages=[];render();document.querySelector('.roster').scrollLeft=scroll;});document.querySelector('.composer').onsubmit=e=>{e.preventDefault();const input=document.getElementById('prompt');if(input.value.trim())send(input.value.trim());else input.focus();};document.getElementById('prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();document.querySelector('.composer').requestSubmit();}};document.querySelectorAll('[data-suggestion]').forEach(b=>b.onclick=()=>{const topics=['how AI could change everything','the risks of superintelligence','a surprising prediction'];document.getElementById('prompt').value=`Find a clip of ${people[selected].name} talking about ${topics[b.dataset.suggestion]}`;document.getElementById('prompt').focus();});document.getElementById('new-chat')?.addEventListener('click',()=>{messages=[];render();});}
function send(text){messages.push(text);let log=document.getElementById('conversation');if(!log){log=document.createElement('div');log.id='conversation';log.className='conversation';log.setAttribute('aria-live','polite');document.querySelector('.composer').before(log);}const user=document.createElement('p');user.className='user-message';user.textContent=text;log.append(user);const answer=document.createElement('div');answer.className='assistant-message';answer.innerHTML=`<span class="assistant-icon">${scissors}</span><div><strong>Your clip hunt starts here.</strong><p>This is an interactive design preview. In the finished version, this conversation will search ${people[selected].name}’s transcripts and show clips with playable timestamps.</p><span class="preview-label">PREVIEW · NO SEARCH WAS RUN</span></div>`;log.append(answer);document.getElementById('prompt').value='';document.querySelector('.suggestions')?.setAttribute('hidden','');if(mode==='c')document.querySelector('.room-welcome').hidden=true;if(mode==='d')document.querySelector('.swipe-room').classList.add('has-conversation');log.scrollIntoView({behavior:'smooth',block:'center'});}
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{const toast=document.querySelector('.toast');toast.textContent=b.dataset.nav+' stays available in the finished site. This preview focuses on the homepage.';toast.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.hidden=true,3500);});document.getElementById('credits').onclick=()=>document.getElementById('credits-dialog').showModal();document.getElementById('credit-links').innerHTML=people.map(p=>`<p><a href="https://en.wikipedia.org/wiki/${p.name.replaceAll(' ','_')}" target="_blank" rel="noopener">${p.name} ↗</a></p>`).join('');render();
