const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
const out=process.env.QA_OUTPUT || '.context/homepage-preview/qa-recordings/swipe';fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks=[];
 async function load(p=page){await p.goto((process.env.PREVIEW_URL || 'http://127.0.0.1:4783')+'/concept.html?mode=d');await p.evaluate(()=>document.fonts.ready);await p.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth));}
 const title=async(p=page)=>p.locator('h1').innerText();
 await load();await page.screenshot({path:out+'/desktop.png',fullPage:true});assert.match(await title(),/Sam Altman/);
 let box=await page.locator('.portrait-stage').boundingBox();let x=box.x+box.width/2,y=box.y+70;
 await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x-50,y,{steps:8});assert.match(await title(),/Sam Altman/);assert(await page.locator('.portrait-stage').evaluate(e=>e.classList.contains('dragging')));await page.screenshot({path:out+'/dragging.png'});await page.mouse.up();await page.waitForTimeout(550);assert.match(await title(),/Dario Amodei/);checks.push('PASS Mouse: portrait follows held drag, commits next speaker on release');
 await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+85,y,{steps:8});await page.mouse.up();await page.waitForTimeout(550);assert.match(await title(),/Sam Altman/);checks.push('PASS Reverse drag returns to previous speaker');
 await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x-15,y,{steps:3});await page.waitForTimeout(150);await page.mouse.up();await page.waitForTimeout(550);assert.match(await title(),/Sam Altman/);checks.push('PASS Short drag snaps back without changing speaker');
 await page.locator('.portrait-picker').focus();await page.keyboard.press('ArrowLeft');assert.match(await title(),/Eliezer Yudkowsky/);await page.keyboard.press('ArrowRight');assert.match(await title(),/Sam Altman/);checks.push('PASS Keyboard arrows wrap across all seven speakers');
 const names=['Sam Altman','Dario Amodei','Demis Hassabis','Geoffrey Hinton','Yoshua Bengio','Max Tegmark','Eliezer Yudkowsky'];
 for(const name of names){await page.getByRole('button',{name:'Choose '+name,exact:true}).click();assert.match(await title(),new RegExp(name));assert.equal(await page.locator('.scope strong').innerText(),name);assert.equal(await page.locator('[data-dot][aria-pressed=true]').count(),1);}
 checks.push('PASS All seven dots synchronize headline, chat scope, and selected state');
 await page.locator('.portrait-picker').focus();await page.keyboard.press('Home');await page.waitForTimeout(550);await page.locator('[data-card="1"]').click();assert.match(await title(),/Dario Amodei/);checks.push('PASS Tapping a neighboring portrait selects it');
 await page.getByRole('button',{name:'Choose Sam Altman',exact:true}).click();await page.locator('#prompt').fill('A draft for Sam');await page.getByRole('button',{name:'Next speaker',exact:true}).click();await page.locator('#prompt').fill('A draft for Dario');await page.getByRole('button',{name:'Previous speaker',exact:true}).click();assert.equal(await page.locator('#prompt').inputValue(),'A draft for Sam');await page.locator('#prompt').press('Enter');await page.getByText('PREVIEW · NO SEARCH WAS RUN').waitFor();await page.getByRole('button',{name:'Next speaker',exact:true}).click();assert.equal(await page.locator('#prompt').inputValue(),'A draft for Dario');assert.equal(await page.locator('#conversation').count(),0);await page.getByRole('button',{name:'Previous speaker',exact:true}).click();assert.equal(await page.locator('#conversation').count(),1);await page.getByRole('button',{name:'New chat'}).click();assert.equal(await page.locator('#conversation').count(),0);checks.push('PASS Separate speaker drafts and preview conversations survive switching; New chat clears current session');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:width<500?844:1000});await load();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:out+`/width-${width}.png`,fullPage:true});}checks.push('PASS Responsive layouts at 320, 390, 768, and 1440 pixels, with no page overflow');
 await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Next speaker',exact:true}).click();assert.equal(await page.locator('[data-card="1"]').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');checks.push('PASS Reduced-motion preference disables carousel animation');
 const touch=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});touch.on('pageerror',e=>errors.push(e.message));await load(touch);const cdp=await touch.context().newCDPSession(touch);const area=await touch.locator('.portrait-stage').boundingBox();x=area.x+area.width/2;y=area.y+70;
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-i*11,y}]});await touch.waitForTimeout(16);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touch.waitForTimeout(550);assert.match(await title(touch),/Dario Amodei/);checks.push('PASS Native Chromium touchscreen swipe selects next speaker');
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-70,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await touch.waitForTimeout(550);assert.match(await title(touch),/Dario Amodei/);checks.push('PASS Cancelled touch gesture restores current selection');
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=6;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+2,y:y-i*12}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.match(await title(touch),/Dario Amodei/);checks.push('PASS Vertical touch gesture does not change speaker');
 await touch.screenshot({path:out+'/touch-dario.png',fullPage:true});assert.deepEqual(errors,[]);checks.push('PASS No JavaScript errors');fs.writeFileSync(out+'/verification.txt',new Date().toISOString()+'\n'+checks.join('\n')+'\nLocal prototype only. No live searches or deployment.\n');console.log(checks.join('\n'));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
